### ISSUE TITLE
Validation on ImageMetadata's "directory" field

### ISSUE THREAD

**Issue by jczech** [brain-image-library/bil_site#102]
First, we should make sure it's valid POSIX path. Also, we should make sure it doesn't try to escape the landing zone. For example, if we give them something like "username@somehost:/blahblah/2018/07/5a6bf79f-3209-4634-a7ab-7ad7d1dc078f", they shouldn't list one of the directory fields as say "../../../my_data"

**Comment by ropelews** [comment]
obsolete due to separate validate/submit
