### ISSUE TITLE
UI in collection creation process gives wrong target directory name

### ISSUE THREAD

**Issue by dsimmel** [brain-image-library/bil_site#113]
When creating a new collection, the UI reports near the bottom that the new collection will be created with a target directory named with one hash, e.g., dsimmel@submit.brainimagelibrary.org:/bil/lz/dsimmel/fbcbe81909dda61f but then after hitting 'Save' the created collection shows a different target directory name, e.g., /bil/lz/dsimmel/f25c557839a0cb8f

The actual directory created is the latter one: /bil/lz/dsimmel/25c557839a0cb8f

Please fix the earlier UI message to be consistent with the actual target directory created.

**Comment by ropelews** [comment]
fixed
