### ISSUE TITLE
New collection directory should be owned by bil:bil

### ISSUE THREAD

**Issue by dsimmel** [brain-image-library/bil_site#114]
When creating a new collection directory, the ownership of that directory currently appears as bil:ib5fp4p, e.g.,

[dsimmel@submit dsimmel]$ ls -ld /bil/lz/dsimmel/f25c557839a0cb8f
drwxrwx---+ 2 bil ib5fp4p 33280 Sep 14 14:35 /bil/lz/dsimmel/f25c557839a0cb8f

The directory should be owned by group bil instead - please chown bil:bil by default accordingly.

**Comment by ropelews** [comment]
fixed
