### ISSUE TITLE
Metadata schema of uploaded spreadsheet is not being properly validated

### ISSUE THREAD

**Issue by ropelews** [brain-image-library/bil_site#115]
Metadata schema of uploaded spreadsheet is not being properly validated. What is happening is people are uploading spreadsheets with incorrect header information. Instead of presenting information to the user rejecting the upload, no error is raised and this is getting blank fields in the database.

**Comment by ltuite96** [comment]
Liz and Myself took care of this issue, there was a preexisting check for this already in place, however it was checking over a list 'required_metadata' that was not only commented out but did not contain the current required metadata fields. 

We've updated this error check so it properly checks if all of the items inside the 'required_metadata' list are present.

**Comment by ecpantalone** [comment]
this should be resolved with 91b476de6a59d10c073b034f307266f5b8dcff82
