### ISSUE TITLE
Fix Metadata Strings prior to insert so they do not contain \r (^M) characters

### ISSUE THREAD

**Issue by ropelews** [brain-image-library/bil_site#135]
Need to ensure that all strings of metadata are stripped of special characters like ^M (or cr/lf) prior to inserting in the database. 
 
These strings cause problems if we try to export data to a tab delimited spreadsheet (or display in an HTML page). Here is how to spot the problem after such a string with ^M has been inserted into the the database (notice the \r and multi-line display):

 bil_site_bil_2=# select id,description from ingest_collection where id=642;
 id  |                                                                                  description
-----+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 642 | 1708 neuron reconstructions in swc format from high-resolution images collected with the fMOST technology. \r                                                                 +
     | \r                                                                                                                                                                            +
     | Each reconstruction has three files:\r                                                                                                                                        +
     | "original": reconstruction performed by a human using Vaa3D\r                                                                                                                 +
     | "registered": original reconstruction registered into the mouse Common Coordinate Framework by our collaborators using a combination of automated and semi-automated methods\r+
     | "downsampled": original reconstruction downsampled by a factor of 32 in xy and by 8 in z
(1 row)

**Comment by ltuite96** [comment]
I've created an error check that detects if any escape characters are present in the data, the error catches the escape character, flags it, and returns a message to the user explaining that the data submitted contains an illegal character.

**Comment by dsimmel** [comment]
Is this as simple as running files through dos2unix to remove them?

**Comment by ltuite96** [comment]
Eventually yes, for the sake of time and priority we'll just be flagging the error and the location for the user to physically remove them.

**Comment by ecpantalone** [comment]
this is resolved with https://github.com/brain-image-library/bil_site/commit/8bbbe2a24f660e14835a0e9d31cb57675bc337c5
