### ISSUE TITLE
Add Django groups for the main submission sites/labs

### ISSUE THREAD

**Issue by jczech** [brain-image-library/bil_site#14]
We need to add Django groups for the three main submission sites (or maybe break it down by lab), including CSHL, USC, and the Allen Institute. Additionally, I'm imagining everyone in a group can see everyone else's metadata in that group. As such, we'll need some way for labs/sites to administer these groups, but security can be handled in a subsequent issue.

**Comment by SeanDeitrich** [comment]
I added groups for each one through the Django admin interface - I imagine this may need to be done again when we have it up and running on DXC or whatever machine we are using to serve the site.
No functionality yet but the groups are there for me at least.

**Comment by ropelews** [comment]
Obsolete
