### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by ecpantalone** [brain-image-library/bil_site#151]
Currently updating the Django version also requires a bump in the Django-filter version
this appears to break our PAM authentication implementation.

To address this, I'm going to:
- [ ] create a new login function (login2 or something) so as to not touch the current set up
- [ ] see what can be upgraded and see if it truly is the PAM authentication that is breaking or blocking
- [ ] hopefully fix from that discovery

**Comment by ltuite96** [comment]
New login function wasn't needed, conflict between the django.pam version was causing the inability to login. This has been updated and merged to Dev branch. This is resolved with commit: https://github.com/brain-image-library/bil_site/commit/3344f620ddfadc53b70c96835e975e6e808d787f
