### ISSUE TITLE
Give users the capability to link lower level data with higher level data

### ISSUE THREAD

**Issue by ltuite96** [brain-image-library/bil_site#152]
Possible Use Cases:
 - FMOST: raw data has been submitted as its own collection, later on secondary data is uploaded that needs to be linked to the initial raw data (SWC files). 
 - Hongwei Dong: Hongwei submits raw data, aligned data, and warped data together in a collection. Be able to link these different types together. 
 - Spatial Transcriptomics: image files and csv files. Image files can be from more than 1 experiment
 - Patch-seq: image files and SWC files submitted in the same collection.

**Comment by ropelews** [comment]
See issue #159 for First (FMOST-SWC) and last (Patch-seq-SWC).

**Comment by ropelews** [comment]
Closed/replaced by issue: https://github.com/brain-image-library/bil_site/issues/169
