### ISSUE TITLE
Cennot re-upload metadata sheet with the same name for a single submission

### ISSUE THREAD

**Issue by MariahKenney** [brain-image-library/bil_site#220]
During ingest, if the metadata needs to be uploaded more than once, currently you need to change the file name between each upload for any changes to be reflected in the upload.

**Comment by ltuite96** [comment]
We could keep the same functionality of multiple paper trail uploads if we ran a check on the /etc/ directory to see if that filename already exists. Maybe even not that far, just an additional try except that automatically appends a few unique characters to the filename before final ingestion
