### ISSUE TITLE
Submit a collection

### ISSUE THREAD

**Issue by jczech** [brain-image-library/bil_site#27]
We need a way to "submit" a collection. For now, this could be as simple as a button that sets the associated metadata and data to locked. If metadata and data are locked, we should prevent these from being edited or deleted. Also, we'd eventually want to change the remote dirs permissions, but let's save that for a follow-up issue.

**Comment by SeanDeitrich** [comment]
Create collection is currently bugged for me - getting a no column exists for ingest_imagemetadata.sex
Looking into it

**Comment by SeanDeitrich** [comment]
I added the button to the collection detail template but it has no functionality currently.

Should we use ajax to give it functionality? If not, how do we give it functionality?

**Comment by jczech** [comment]
Completed with 8b920eedbe5e12172cc2aeeef413e5afb587cae7
