### ISSUE TITLE
Request Storage Area is Broken

### ISSUE THREAD

**Issue by SeanDeitrich** [brain-image-library/bil_site#29]
The request storage area button has no functionality and stalls the page. 
Didn't we have it set so that it creates a UUID fake path? Did we remove that functionality on purpose?

**Comment by jczech** [comment]
A remote directory is actually created now. The README has the updated instructions.

Make sure RabbitMQ is installed. You also need to add IMG_DATA_USER and IMG_DATA_HOST to your site.cfg file. Set up passwordless authentication with ssh keys. Also, be sure your requirements are up-to-date (e.g. "pip install -r requirements.txt") so you have  Fabric and Celery. Then run Celery in a separate terminal like this: celery -A bil_site worker -l info

You should be good to go after this. Let me know if you run into any problems.
