### ISSUE TITLE
If no User ID inform user to create an Xsede Portal ID

### ISSUE THREAD

**Issue by ltuite96** [brain-image-library/bil_site#58]
https://portal.xsede.org/#/guest

**Comment by ltuite96** [comment]
This page shouldn't be functional with the database yet, we should create the page and turn it over to Derek on the authentication side of things for what way we should go with it.

**Comment by jczech** [comment]
Added XSEDE link with commit d13ed2b043db29d94c1e262e4dd373bebd577489
