### ISSUE TITLE
Add new fields to metadata

### ISSUE THREAD

**Issue by jczech** [brain-image-library/bil_site#9]
We should use the full set of fields that were used in the spreadsheet template sent out to the various submitting sites as listed below:
 
OrganizationName
LabName
SubmitterEmail
ProjectName
ProjectDescription
ProjectFunder
ProjectFunderID
TaxonomyName
BackgroundStrain
TransgenicLineName
Age
AgeUnit
Sex
Organ
OrganSubstructure
Assay
SlicingDirection
ImageFilenamePattern

We currently already use a subset of these fields in the metadata model.

Additionally, we should also evaluate what we would like to change about this list. What fields are we missing? Should any existing fields be changed? A lot of these questions could perhaps be additional issues. For this issue, just focus on the fields listed above.

**Comment by SeanDeitrich** [comment]
Done.
